### ISSUE TITLE
This method will need to be changed for each type of scrambling we come up with. Fine for now, since it's only two types.

### ISSUE THREAD

**Issue by maxyodedara5** [thijsfranck/the-dynamic-typists#10]
This method will need to be changed for each type of scrambling we come up with. Fine for now, since it's only two types.

This is a candidate for refactoring if we decide to add more types of scrambling. The [strategy pattern](https://refactoring.guru/design-patterns/strategy) is a good fit here.

_Originally posted by @thijsfranck in https://github.com/thijsfranck/the-dynamic-typists/pull/8#discussion_r1314172253_

**Comment by Istalantar** [comment]
Not relevant anymore
